using System;

namespace InterportCargo.Web.Models
{
    /// <summary>
    /// Represents a prepared quotation that is generated by a Quotation Officer
    /// in response to a customer's quotation request.
    /// This aligns with user stories I3, I4, I5, and I6.
    /// </summary>
    public class Quotation
    {
        /// <summary>
        /// Primary Key - Unique identifier for the quotation.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign key linking this quotation to the original quotation request.
        /// </summary>
        public int QuotationRequestId { get; set; }

        /// <summary>
        /// Navigation property to the related quotation request entity.
        /// Optional use for EF Core relationships.
        /// </summary>
        public QuotationRequest? Request { get; set; }

        /// <summary>
        /// Human-readable quotation number (e.g., QTN-0001).
        /// </summary>
        public string QuotationNumber { get; set; } = string.Empty;

        /// <summary>
        /// Date and time (UTC) when this quotation was issued.
        /// </summary>
        public DateTime DateIssued { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Container type being quoted (e.g., 20GP, 40GP, or LCL).
        /// </summary>
        public string ContainerType { get; set; } = "20GP";

        /// <summary>
        /// Description of the job scope (import/export, packing, quarantine, etc.).
        /// </summary>
        public string Scope { get; set; } = string.Empty;

        /// <summary>
        /// Base charge for this quotation, taken from the rate schedule.
        /// </summary>
        public decimal ChargesBase { get; set; }

        /// <summary>
        /// Applicable depot charge for this quotation.
        /// </summary>
        public decimal ChargesDepot { get; set; }

        /// <summary>
        /// Delivery charge for LCL shipments (applies only if container type is 'LCL').
        /// </summary>
        public decimal ChargesLcl { get; set; }

        /// <summary>
        /// Discount amount (if applied) based on discount criteria (User Story I5).
        /// </summary>
        public decimal DiscountApplied { get; set; }

        /// <summary>
        /// Computed total cost: (Base + Depot + LCL - Discount).
        /// </summary>
        public decimal Total => ChargesBase + ChargesDepot + ChargesLcl - DiscountApplied;

        /// <summary>
        /// Current status of the quotation (Pending, Preparing, Sent, Accepted, Rejected).
        /// </summary>
        public QuotationStatus Status { get; set; } = QuotationStatus.Sent;
    }
}
